openapi: 3.0.2
info:
  title: 'Yahoo!広告 ディスプレイ広告 API リファレンス β版 / Yahoo! Ads Display Ads API Reference β
    Version'
  version: 'v0'
  description: |
    <div lang="ja">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。<br>
    「Try it out」のご利用には、事前にアプリケーションの登録が必要です。また、アプリケーションのリダイレクトURIの1つに<br>
    https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.htmlを登録してください。
    </div>
    <div lang="en">Display Ads API Web Services supported in Yahoo! Ads API.<br>
    When you use "Try it out", you need to register your application in advance.<br>
    As one of redirect URI for application, you need to set "https://yahoojp-marketing.github.io/ads-display-api-documents/oauth2-redirect.html".
    </div>

components:
  securitySchemes:
    oAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://biz-oauth.yahoo.co.jp/oauth/v1/authorize
          tokenUrl: https://biz-oauth.yahoo.co.jp/oauth/v1/token
          scopes:
            yahooads: アプリケーションを経由したYahoo!広告の各機能の操作/Operation by each function of Yahoo!
              Ads via applications.
security:
- oAuth: [yahooads]

servers:
- url: https://ads-display.yahooapis.jp/api/v0

tags: []
paths: {}
